//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nuget.PackageIndex.Manager {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nuget.PackageIndex.Manager.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action to be done with package index: Build, Rebuild, Clean, Add, Remove, Query, Dump..
        /// </summary>
        internal static string ActionDescription {
            get {
                return ResourceManager.GetString("ActionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested action is unrecognized..
        /// </summary>
        internal static string ActionUnrecognized {
            get {
                return ResourceManager.GetString("ActionUnrecognized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument expected some value &apos;{0}&apos;.
        /// </summary>
        internal static string ArgumentExpectedValue {
            get {
                return ResourceManager.GetString("ArgumentExpectedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument is a flag and does not support values &apos;{0}&apos;.
        /// </summary>
        internal static string ArgumentIsFlag {
            get {
                return ResourceManager.GetString("ArgumentIsFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dumped index contents to: {0}.
        /// </summary>
        internal static string DumpMessage {
            get {
                return ResourceManager.GetString("DumpMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force selected action..
        /// </summary>
        internal static string ForceDescription {
            get {
                return ResourceManager.GetString("ForceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display this message..
        /// </summary>
        internal static string HelpDescription {
            get {
                return ResourceManager.GetString("HelpDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect argument format &apos;{0}&apos;.
        /// </summary>
        internal static string IncorrectArgumentFormat {
            get {
                return ResourceManager.GetString("IncorrectArgumentFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid argument pattern &apos;{0}&apos;.
        /// </summary>
        internal static string InvalidArgumentPattern {
            get {
                return ResourceManager.GetString("InvalidArgumentPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results ....
        /// </summary>
        internal static string NoResults {
            get {
                return ResourceManager.GetString("NoResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query a package: package=YourPackageName..
        /// </summary>
        internal static string PackageDescription {
            get {
                return ResourceManager.GetString("PackageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package Index Manager.
        /// </summary>
        internal static string PackageIndexManagerTitle {
            get {
                return ResourceManager.GetString("PackageIndexManagerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify package to be added to the index..
        /// </summary>
        internal static string PackageIsMissingToAdd {
            get {
                return ResourceManager.GetString("PackageIsMissingToAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify package to be removed from index..
        /// </summary>
        internal static string PackageIsMissingToRemove {
            get {
                return ResourceManager.GetString("PackageIsMissingToRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify package or type to be queried from index..
        /// </summary>
        internal static string PackageOrTypeIsMissing {
            get {
                return ResourceManager.GetString("PackageOrTypeIsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No output to the log or console..
        /// </summary>
        internal static string QuietDescription {
            get {
                return ResourceManager.GetString("QuietDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument&apos;s pattern can not be empty.
        /// </summary>
        internal static string String1ArgumentPatternCanNotBeEmpty {
            get {
                return ResourceManager.GetString("String1ArgumentPatternCanNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time elapsed: {0}.
        /// </summary>
        internal static string TimeElapsed {
            get {
                return ResourceManager.GetString("TimeElapsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query a type: type=YourType..
        /// </summary>
        internal static string TypeDescription {
            get {
                return ResourceManager.GetString("TypeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized argument &apos;{0}&apos;.
        /// </summary>
        internal static string UnrecognizedArgument {
            get {
                return ResourceManager.GetString("UnrecognizedArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detailed output to the log or console..
        /// </summary>
        internal static string VerboseDescription {
            get {
                return ResourceManager.GetString("VerboseDescription", resourceCulture);
            }
        }
    }
}
